before_script:
   - npm install -g gulp
language: node_js
node_js:
  - "7"
script: gulp build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  acl: public_read
